site_name: yy6080-yy6080新视觉影院
site_author: yy6080
site_description: yy6080是一家专注于影视制作与发行的yy6080影视传媒制作公司，yy6080app致力于为用户提供优质的影视内容。其官方网站汇集了丰富的电影、电视剧、综艺等资源，支持在线观看与高清下载。网站界面简洁，分类清晰，涵盖最新热播剧集、经典影片推荐及独家原创内容，满足不同用户的观影需求。同时提供会员服务，享受无广告、蓝光画质等特权，打造沉浸式观影体验。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
